module.exports = {
    ERR0001: 'Database query failed',
    ERR0002: 'Parameters are empty',
    ERR0003: 'Error while hashing password. Please try again.',
    ERR0004: 'Username already exists.',
    ERR0005: 'Username is required.',
    ERR0006: 'Password is required.',
    ERR0007: 'Password confirm is required.',
    ERR0008: 'Password does not match.',
    ERR0009: 'Fullname is required.',
    ERR0011: 'Email is required.',
    ERR0012: 'Email format is invalid.',
    ERR0014: 'Password length must be more than 8 characters.',
    ERR0015: 'Cannot cannot to DB',
    ERR0016: 'Phone is required',
    ERR0017: 'Username is not registered yet',
    ERR0018: 'Password is incorrect',
    ERR0019: 'Data already registered.',
}